### ISSUE TITLE
Ruler Increments

### ISSUE THREAD

**Issue by s80s77** [Bluegrams/ScreenRuler#12]
When I open the ruler and change it to Inches, the increments are in 10ths.  Most rulers are set to 16ths.  Is there a way to change this?

**Comment by alxnull** [comment]
Hi @s80s77,

I am not very familiar with imperial units. If I understood you correctly (and after looking up inch ruler scales) the ruler scale between two inches is usually divided into 8 or 16 units instead of 10? If dividing into 10 parts is uncommon, we should probably just switch to dividing by 16 units by default for inches.

**Comment by s80s77** [comment]
Yes, that would be awesome!

Sent from my iPhone--please excuse any typos

Sue Ellen Sopher
Maconaquah Middle School
Project Lead the Way
594 E 800 S
Bunker Hill, IN 46914
765-689-9131 x4308
sophers@maconaquah.k12.in.us

**Comment by alxnull** [comment]
@s80s77 I implemented the change as suggested. It will be available with the next released version. Thanks for your feedback!

**Comment by s80s77** [comment]
Thank you!!!!
